server:
  port: 9001


spring:
  application:
    name: microservicecloud-config-server


  cloud:
    config:
      server:
        git:
          uri: https://github.com/JerrySunTao/taosun-spring-cloud-config-test.git # git仓库的地址
#          search-paths: chapter6/springcloud-config  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: #Git仓库用户名
          password: #Git仓库密码