server:
  port: 9527


spring:
  application:
    name: microservicecloud-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: taosun-microservicecloud
  company.name: www.taosun.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


#zuul:
#  prefix: /taosun #访问前缀
#  ignored-services: "*" #不能使用微服务名访问，只能使用别名
#  routes:
#    microservicecloud-dept: /mydept/** #前面为注册的微服务名: 微服务别名,因此可以注册多个微服务名
#    microservicecloud-feign: /myfeign/**


#   mydept.serviceId: microservicecloud-dept 这种写法和上面一样
#   mydept.path: /mydept/**
#最终访问的url:http://myzuul.com:9527/taosun/mydept/dept/get/2

