server:
  port: 9002


spring:
  application:
    name: microservicecloud-turbine
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

  instance:
    instance-id: microservicecloudConsumerHystrixTurbine-9002
    prefer-ip-address: true

turbine:
  appConfig: microservicecloud-feign
  clusterNameExpression: "'default'"
